apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections  4096;  ## Default: 1024
    }


    http {
        upstream functions {
            server pj-fn-api.default;
            # server pj-fn-api.default/r/app/v2/;
        }
        server {
            listen 80;

            location / {
                rewrite ^(.*)$  /r/app/$1 break;
                proxy_redirect off;
                proxy_set_header Host $http_host;
                proxy_pass http://functions;
                # return 301 http://pj-fn-api.default/r/app/v1/;
            }
        }
    }