apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: appservice
  namespace: default
spec:
  destination:
    name: appservice
  route:
  - labels:
      version: v1
    weight: 100
